services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.36.6
    container_name: weaviate
    environment:
      - TZ=${TZ}
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:-false}
      - AUTHENTICATION_APIKEY_ENABLED=${AUTHENTICATION_APIKEY_ENABLED:-true}
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=${AUTHENTICATION_APIKEY_ALLOWED_KEYS:-change-me-api-key}
      - AUTHENTICATION_APIKEY_USERS=${AUTHENTICATION_APIKEY_USERS:-admin}
    ports:
      - 8089:8080
      - 50051:50051
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/weaviate
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
