services:
  emqx_nanomq:
    image: emqx/nanomq:0.23.7-10-slim
    container_name: emqx_nanomq
    environment:
      - TZ=${TZ}
    ports:
      - 1883:1883 
      - 8083:8083
      - 8081:8081
      - 18083:18083
    healthcheck:
      test: ["CMD", "/usr/local/nanomq/nanomq", "help"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ${APP_DATA_DIR}/data:/etc
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.emqx_nanomq-web-redirect.redirectscheme.scheme: https
      traefik.http.services.emqx_nanomq.loadbalancer.server.port: 18083
      # Web
      traefik.http.routers.emqx_nanomq-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.emqx_nanomq-insecure.entrypoints: web
      traefik.http.routers.emqx_nanomq-insecure.service: emqx_nanomq-web
      traefik.http.routers.emqx_nanomq-insecure.middlewares: emqx_nanomq-web-redirect
      # Websecure
      traefik.http.routers.emqx_nanomq.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.emqx_nanomq.entrypoints: websecure
      traefik.http.routers.emqx_nanomq.service: emqx_nanomq-web
      traefik.http.routers.emqx_nanomq.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.emqx_nanomq-local-insecure.rule: Host(`emqx_nanomq.${LOCAL_DOMAIN}`)
      traefik.http.routers.emqx_nanomq-local-insecure.entrypoints: web
      traefik.http.routers.emqx_nanomq-local-insecure.service: emqx_nanomq-web
      traefik.http.routers.emqx_nanomq-local-insecure.middlewares: emqx_nanomq-web-redirect
      # Local domain secure
      traefik.http.routers.emqx_nanomq-local.rule: Host(`emqx_nanomq.${LOCAL_DOMAIN}`)
      traefik.http.routers.emqx_nanomq-local.entrypoints: websecure
      traefik.http.routers.emqx_nanomq-local.service: emqx_nanomq-web
      traefik.http.routers.emqx_nanomq-local.tls: true
      runtipi.managed: true
