services:
  emqx_nanomq:
    image: emqx/nanomq:0.23.7-10-slim
    container_name: emqx_nanomq
    environment:
      - TZ=${TZ}
    ports:
      - 1883:1883 
      - 8083:8083
      - 8081:8081
      - 18083:18083
    healthcheck:
      test: ["CMD", "/usr/local/nanomq/nanomq", "help"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ${APP_DATA_DIR}/data:/etc
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
